---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workloads-initialization
  namespace: flux-system
spec:
  prune: true
  dependsOn:
  - name: crossplane
  interval: 2m0s
  path: ./workloads/cluster-name
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
---