---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-k8s-provider
  namespace: flux-system
spec:
  dependsOn:
  - name: crossplane-core
  interval: 3m0s
  path: ./tools/crossplane/crossplane-k8s-provider
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
